name: Build

on:
  push:
    branches:
      - master

jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Trigger Release Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const workflow_id = 'release.yml';
            const ref = 'refs/heads/master';
            await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref,
              inputs: {
                release_type: 'patch' // Default value, can be changed by user input in the release workflow
              }
            });
