name: Build/Publish

on:
  push:
    tags:
      - 'v*.*.*'         # Matches tags like v1.2.3
      - 'v*.*.*-beta.*'  # Matches tags like v1.2.3-beta.0

jobs:
  release:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        
      # - name: Run publish script
      #   run: npm run publish

      - name: Build/release Electron app
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: --publish onTag